---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: three-tier-app-backend-dev
  namespace: three-tier-app
  labels:
    app: three-tier-app-backend
    env: dev
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: three-tier-app-backend
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: argo-kustomize-update-image
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: "dev"
            - name: warehouseImage
              value: "ghcr.io/kishoredurai/three-tier-applications/backend"
            - name: valuesFileAbsolutePath
              value: three-tier-app/backend/overlay/dev
            - name: syncArgoApp
              value: "true"
            - name: argoAppName
              value: "three-tier-app-backend-dev"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: three-tier-app-backend-qa
  namespace: three-tier-app
  labels:
    app: three-tier-app-backend
    env: qa
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name:  three-tier-app-backend
      sources:
        stages:
          - three-tier-app-backend-dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: argo-kustomize-update-image
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: "qa"
            - name: warehouseImage
              value: "ghcr.io/kishoredurai/three-tier-applications/backend"
            - name: valuesFileAbsolutePath
              value: three-tier-app/backend/overlay/qa
            - name: syncArgoApp
              value: "true"
            - name: argoAppName
              value: "three-tier-app-backend-qa"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: three-tier-app-backend-stage
  namespace: three-tier-app
  labels:
    app: three-tier-app-backend
    env: stage
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: three-tier-app-backend
      sources:
        stages:
          - three-tier-app-backend-qa
  promotionTemplate:
    spec:
      steps:
        - task:
            name: argo-kustomize-update-image
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: "stage"
            - name: warehouseImage
              value: "ghcr.io/kishoredurai/three-tier-applications/backend"
            - name: valuesFileAbsolutePath
              value: three-tier-app/backend/overlay/stage
            - name: syncArgoApp
              value: "true"
            - name: argoAppName
              value: "three-tier-app-backend-stage"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: three-tier-app-backend-prod
  namespace: three-tier-app
  labels:
    app: three-tier-app-backend
    env: prod
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: three-tier-app-backend
      sources:
        stages:
          - three-tier-app-backend-stage
  promotionTemplate:
    spec:
      steps:
        - task:
            name: argo-kustomize-update-image
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: "prod"
            - name: warehouseImage
              value: "ghcr.io/kishoredurai/three-tier-applications/backend"
            - name: valuesFileAbsolutePath
              value: three-tier-app/backend/overlay/prod
            - name: syncArgoApp
              value: "false"
            - name: argoAppName
              value: "three-tier-app-backend-prod"