---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: three-tier-app-backend
  namespace: three-tier-app
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/kishoredurai/three-tier-applications/backend
        imageSelectionStrategy: NewestBuild

