apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-of-appsets
  namespace: argocd   # <-- this must be in argocd, so ArgoCD can see it
spec:
  template:
    metadata:
      name: Application-Deployment
    spec:
      project: app-deployment
      source:
        repoURL: https://github.com/kishoredurai/kargo-poc
        targetRevision: master
        path: app-of-app   # this path contains your backend ApplicationSet YAML
      destination:
        namespace: three-tier-app   # where to deploy the child ApplicationSet
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true